service: auth-service

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'

  environment:
    DEFAULT_LOGIN: jake@example.com
    DEFAULT_PASSWORD: 123

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - execute-api:Invoke
      Resource: '*'

functions:
  BasicAuthorizer:
    handler: src/auth.handler
    description: Basic Authorization In Lambda
    environment:
      DEFAULT_LOGIN: ${DEFAULT_LOGIN}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
