service: import-service

frameworkVersion: "3"

custom:
  bucket: jake-uploaded

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  environment:
    AUTHORIZER: BasicAuthorizer
    NODE_ENV: dev
    IMAGE_UPLOAD_BUCKET: ${self:custom.bucket}
    SQS_QUEUE:
       Ref: CatalogItemsQueue
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource: '*'
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:ChangeMessageVisibility
            - sqs:GetQueueUrl
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [ "${provider.environment.SQS_QUEUE}", Arn ]
        - Effect: Allow
          Resource: "*"
          Action:
            - "sns:*"

plugins:
  - serverless-plugin-typescript

functions:
  importProductsFile:
    handler: src/upload.handler
    events:
      - http:
          path: /import
          method: POST
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
          authorizer:
            type: TOKEN
            name: "${provider.environment.AUTHORIZER}"
            identitySource: method.request.header.Authorization
            arn:
              Fn::GetAtt: [ "${provider.environment.AUTHORIZER}", Arn ]
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: src/parser.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
    CatalogItemsQueue:
      Type: AWS::SQS::Queue

