service: import-service

frameworkVersion: "3"

custom:
  bucket: jake-uploaded

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  environment:
    NODE_ENV: dev
    IMAGE_UPLOAD_BUCKET: ${self:custom.bucket}
    SQS_QUEUE: receiverQueue
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource: '*'
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:ChangeMessageVisibility
            - sqs:GetQueueUrl
            - sqs:GetQueueAttributes
          Resource:
            - Fn::GetAtt: [ "${provider.environment.SQS_QUEUE}", Arn ]
        - Effect: Allow
          Resource: "*"
          Action:
            - "sns:*"

plugins:
  - serverless-plugin-typescript

functions:
  importProductsFile:
    handler: src/upload.handler
    events:
      - http:
          path: /import
          method: POST
          cors: true
  importFileParser:
    handler: src/parser.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
    CatalogItemsQueue:
      Type: AWS::SQS::Queue
    CreateProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Create Product Notification
        SnsTopicName: createProductTopic
    EmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        EndpointIdentifier:

