service: import-service

frameworkVersion: "3"

custom:
  bucket: uploads

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-1'
  lambdaHashingVersion: '20201221'
  environment:
    NODE_ENV: dev
    IMAGE_UPLOAD_BUCKET: ${self:custom.bucket}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource: '*'

functions:
  imageUpload:
    handler: src/functions/imageUpload.handler
    events:
      - http:
          path: /image-upload
          method: POST
          cors: true

resources:
  Resources:
    ImageUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
